version: '2'

services:
  music-buildui:
    build:
      context: ./src/
      dockerfile: ui/Dockerfile
    image: music-ui:latest
    container_name: music-buildui
    volumes:
      - ./src/:/srv/src
    ports:
        - 3000:3000

