version: '2'

services:
  music-buildui:
    build:
      context: ./src/
      dockerfile: ui/Dockerfile
    image: music-ui:latest
    container_name: music-buildui
    volumes:
      - ./src/:/srv/src
    ports:
        - 3000:3000

  music-midi:
    build:
      context: ./src/
      dockerfile: audio_to_midi/Dockerfile
    image: music-midi:latest
    container_name: music-midi
    volumes:
      - ./src/:/srv/src

