version: '2'

services:
  music-ui:
    build:
      context: ./src/ui
      dockerfile: Dockerfile
    image: music-ui:latest
    container_name: music-ui
    volumes:
      - ./src/ui/src:/srv/src/ui/src
      - ./src/ui/public:/srv/src/ui/public
    ports:
      - 3000:3000
    environment:
      - PUBLIC_URL=http://localhost:3000/

#  music-midi:
#    build:
#      context: ./src/
#      dockerfile: audio_to_midi/Dockerfile
#    image: music-midi:latest
#    container_name: music-midi
#    volumes:
#      - ./src/:/srv/src

