version: '2'

services:
  music-buildui:
    build:
      context: ./src/
      dockerfile: ui/Dockerfile
    image: music-ui:latest
    container_name: music-buildui
    volumes:
      - ./src/:/srv/src
    ports:
        - 3000:3000

  music-buildui2:
    build:
      context: ./src/
      dockerfile: ui2/Dockerfile
    image: music-ui2:latest
    container_name: music-buildui2
    volumes:
      - ./src/:/srv/src
    ports:
        - 8000:8000

