// export const ADD_ARTICLE = "ADD_ARTICLE";

export const START_FRAMEWORK_ENDPOINTS_FETCH='START_FRAMEWORK_ENDPOINTS_FETCH'
export const END_FRAMEWORK_ENDPOINTS_FETCH='END_FRAMEWORK_ENDPOINTS_FETCH'
export const FRAMEWORK_FETCH='FRAMEWORK_FETCH'
export const TOGGLE_GAME_MODE='TOGGLE_GAME_MODE'
export const START_MATCHES_FETCH='START_MATCHES_FETCH'
export const END_MATCHES_FETCH='END_MATCHES_FETCH'
