name: On Merge Main

on:
  push:
    branches:
      - main

jobs:
  build_and_test-ui:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: arn:aws:iam::408799413549:role/github-actions-music-ui
          aws-region: us-west-2

      - name: build and publish
        run: |
          cd src/ui
          yarn install --frozen-lockfile
          yarn build
          aws s3 sync --delete --quiet dist/ s3://music-ui/prod/
          aws cloudfront create-invalidation --distribution-id E2FN07MF5Y5JDB --paths "/*"
